name: Push/PR

on:
  push:
    branches:
      - main
      - master
      - renovate/**
  pull_request:
  workflow_dispatch:

jobs:
  push-pr:
    uses: newrelic/coreint-automation/.github/workflows/reusable_push_pr.yaml@v3
    with:
      integration: kafka
      run_integration_nix: false
    secrets: inherit

# This is currently not covered by reusable workflow due to the retry mechanism
  test-integration-nix:
    name: Run integration tests on *Nix
    runs-on: ubuntu-22.04
    env:
      ORIGINAL_REPO_NAME: ${{ github.event.repository.full_name }}
      NRJMX_VERSION: '2.3.2' ## this is needed in the makefile
    defaults:
      run:
        working-directory: src/github.com/${{env.ORIGINAL_REPO_NAME}}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: src/github.com/${{env.ORIGINAL_REPO_NAME}}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'src/github.com/${{env.ORIGINAL_REPO_NAME}}/go.mod'
      - name: Integration test
        # One of the integration consumer tests is not working as expected to the environment bootstrap, to keep it
        run: for i in 1 2 3; do make integration-test && break; done
