name: Create release artifacts

on:
  release:
    types:
      - released
    tags:
      - 'v*'

jobs:
  release:
    uses: newrelic/coreint-automation/.github/workflows/reusable_on_release.yaml@v3
    with:
      integration: kafka
      tag: ${{ github.event.release.tag_name }}
      publish_schema: "ohi-jmx"
    secrets: inherit
